preprocess:
  build: https://github.com/haw-mip02/analysis-preprocess.git
  links:
    - database:mongodb
database:
  build: https://github.com/haw-mip02/analysis-database.git
  environment:
    MONGODB_USER: "analysis"
    MONGODB_DATABASE: "analysis"
    MONGODB_PASS: "${MONGODB_PASS}"
  volumes:
    - ./db:/data/db
  ports:
    - "27017:27017"
    - "28017:28017"
cache:
  build: https://github.com/haw-mip02/analysis-cache.git
  ports:
    - "6379:6379"
rest:
  build: https://github.com/haw-mip02/analysis-rest.git
  environment:
    MONGODB_PASS: "${MONGODB_PASS}"
  ports:
    - "5000:5000"
  links:
    - database:mongodb
    - cache:redis